version: '3'
services:
  app:
    image: oktav1722/unikmu:latest
    environment:
      - MONGO_URL=mongodb+srv://oktav1722:Oktavanusa17@cluster0.lknvw.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      - PASS_SEC=oktav1722
      - JWT_SEC=oktav2217
      - SESSION_TIME=3d
      - MIDTRANS_SERVER_KEY=SB-Mid-server-ryqIOMaOzUUhJgXmreKW9X_u
      - MIDTRANS_CLIENT_KEY=SB-Mid-client-gVE4X3zaEcJZh1N2
      - BASE_URL=http://localhost:5000/api/
      - ADMIN_EMAIL=admin@gmail.com
      - ADMIN_PASS=admin
      - MIDTRANS_EXPIRED_TIME=15 
      - NODE_ENV=production
      - FRONTEND_URL=https://unikmu.fly.dev
      - PORT=3000
    ports:
      - "3000:3000"


