# fly.toml app configuration file generated for unikmu on 2023-09-19T18:51:43+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "unikmu"
primary_region = "sin"

[build]

[env]
  MONGO_URL = "mongodb+srv://oktav1722:Oktavanusa17@cluster0.lknvw.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
  PASS_SEC = "oktav1722"
  JWT_SEC = "oktav2217"
  SESSION_TIME = "3d"
  MIDTRANS_SERVER_KEY = "SB-Mid-server-ryqIOMaOzUUhJgXmreKW9X_u"
  MIDTRANS_CLIENT_KEY = "SB-Mid-client-gVE4X3zaEcJZh1N2"
  BASE_URL = "http://localhost:5000/api/"
  ADMIN_EMAIL = "admin@gmail.com"
  ADMIN_PASS = "admin"
  MIDTRANS_EXPIRED_TIME = "15 "
  NODE_ENV = "production"
  FRONTEND_URL = "https://1e94-103-105-35-70.ap.ngrok.io"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
